version: '3'
services:
  db:
    image: mariadb:11.4.2
    container_name: project_name_mariadb
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p", "${MARIADB_PASSWORD}",  "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: project_name_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
