#version: '3.9'
#ALERTA: docker-compose.yml: `version` is obsolete"

services:
  driverplan:
    container_name: driverplan
    build:
      context: .
      # infomrar caminho do docker file (caso necessario): <./Dockerfile>
    ports:
      - 8000:8000
    volumes:
      - ./driverplan:/driverplan
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

