# Generated by Django 5.0.6 on 2024-07-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controle", "0002_remove_modelo_viagem_unico_docs_mv_unico_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="viagem_unica",
            name="data_desembarque_efetivo",
        ),
        migrations.RemoveField(
            model_name="viagem_unica",
            name="hora_desembarque_efetivo",
        ),
        migrations.AlterField(
            model_name="viagem_unica",
            name="cep_desembarque",
            field=models.CharField(help_text="desembarque", max_length=256),
        ),
        migrations.AlterField(
            model_name="viagem_unica",
            name="cep_embarque",
            field=models.CharField(help_text="cembarque", max_length=256),
        ),
    ]
