# Generated by Django 4.2.13 on 2024-07-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controle", "0003_remove_viagem_unica_data_desembarque_efetivo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="viagem_unica",
            name="status_cor",
            field=models.CharField(
                choices=[("V", "VERDE"), ("L", "LARANJA")],
                default="LARANJA",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="viagem_unica",
            name="status",
            field=models.CharField(
                choices=[("V", "VERDE"), ("L", "LARANJA")], max_length=1
            ),
        ),
    ]
