# Generated by Django 4.2.13 on 2024-07-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controle", "0004_viagem_unica_status_cor_alter_viagem_unica_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viagem_unica",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "PAGO"),
                    ("A", "PENDENTE"),
                    ("S", "CANCELADO SEM DEBITO"),
                    ("C", "CANCELADO COM DEBITO"),
                ],
                max_length=1,
            ),
        ),
    ]
