# Generated by Django 4.2.13 on 2024-07-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controle", "0005_alter_viagem_unica_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="viagem_unica",
            name="status_cor",
        ),
        migrations.AlterField(
            model_name="viagem_unica",
            name="status",
            field=models.CharField(
                choices=[("P", "PAGO"), ("A", "PENDENTE")], max_length=1
            ),
        ),
    ]
