# Generated by Django 5.0.6 on 2024-06-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.CharField(max_length=100)),
                ('distancia', models.FloatField()),
                ('custo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('pontos_de_parada', models.JSONField(blank=True, default=list)),
                ('destino', models.IntegerField()),
                ('origem', models.IntegerField()),
                ('data_hora', models.DateTimeField()),
                ('motorista', models.IntegerField()),
                ('cliente', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='pendente', max_length=50)),
            ],
        ),
    ]
